### ISSUE TITLE
Show Docker workaround for using HTTP_PROXY

### ISSUE THREAD

**Issue by luebken** [giantswarm/docs-content#11]
The usage of HTTP_PROXY introduced here (https://github.com/giantswarm/docs-content/pull/5) made broke the Docker command.

There is a workaround noted by Kay which should be made available in the docs. It should be described for Linux and Windows. 

```
The problem was, that the Docker client connects to the Docker server over a Unix socket.
But it tried to use the proxy for this, which didn't work.
When I removed it, the connection to the local Docker server worked, but the server couldn't get out.

I had to do two things to fix this:

To prevent the Docker client from using the proxy when connecting to the local server I added
"/var/run/docker.sock" to my "/etc/environment" like this:
no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,/var/run/docker.sock"

To get the server to use the proxy I had to add my proxy to "/etc/default/docker"
export http_proxy=http://<user>:<password>@<host>:<port>
Because the server has to run as root and

Now I can use "swarm" and "docker" together behind a proxy.
```

**Comment by kay-is** [comment]
Yes, I didn't now "where" in the docs it should be put.

**Comment by kordless** [comment]
This issue appears to be discussing a solution for a Linux distribution. I tested setting the HTTP_PROXY settings on OSX and both the CLI and docker commands (via `docker push`) appear to be using the proxy server I am running locally (Charles Proxy).  Given this is a docker related issue and the solution is likely to vary from distribution to distribution, I think the best course of action is to place a note in the docs referring to the StackOverflow solution: http://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

**Comment by marians** [comment]
@luebken Can you please comment on the current status of this? Thanks.

**Comment by marians** [comment]
@luebken @kay-is Closing this, since it's been partly fixed and it's been stale for a while. Please create a new detailed issue if there is anything left to work on here.

**Comment by luebken** [comment]
For the sake of documentation: how is this partly fixed.

**Comment by marians** [comment]
@luebken By the commit https://github.com/giantswarm/docs-content/commit/d394ddc948d2c10756d82c80c9266c4a29e13091

**Comment by luebken** [comment]
thanks
