### ISSUE TITLE
Update documentation landing page

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#13]
This is an update to the current landing page at https://docs.giantswarm.io/.

![docslanding](https://cloud.githubusercontent.com/assets/90237/6879246/f5d92b52-d4ac-11e4-8f44-fbb9983f1e65.png)

Update should include the following changes, as indicated in the mockup:
* move search box to top right under 'get invite' and 'sign in'
* move sub-nav bar left of search box (now at top right)
* update left-side navigation to include language specific examples and advanced uses cases
* add video introduction content under install instructions
* add information on open source docs and opening issues

Depends on content from: #14

**Comment by marians** [comment]
Closing. :8ball:
