### ISSUE TITLE
Write a dedicated page for linking

### ISSUE THREAD

**Issue by luebken** [giantswarm/docs-content#140]
The linking between components and inter-service linking is a rather important and we should write a dedicated page. See https://github.com/giantswarm/app-definition-examples#inter-service-links

**Comment by ZeissS** [comment]
One of our customers ran into this today. Our docs (as of 29.9.15) are not really explaining very well what needs to be done. I guess using the references example as a starting point and integrating it into the the json-reference might be a good start.

**Comment by marians** [comment]
Let me add that the previous comment i mainly about inter service linking.
