### ISSUE TITLE
change download links to HTTPS

### ISSUE THREAD

**Issue by puja108** [giantswarm/docs-content#142]
As mentioned in https://github.com/giantswarm/giantswarm/issues/186#issuecomment-128377024 we now have cloudflare for downloads.giantswarm.io so SSL now works, we just need to update the parts in docs that we are using http

/ping @marians

**Comment by akuckartz** [comment]
:+1: for changing to https.

**Comment by marians** [comment]
Closed via https://github.com/giantswarm/docs-content/pull/144
