### ISSUE TITLE
Update reference landing page

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#15]
Update the reference landing page.

![docsreferencelanding](https://cloud.githubusercontent.com/assets/90237/7124083/507fa6a4-e1db-11e4-95e8-c4a1acbb519a.png)

Update should include the following changes, as indicated in the mockup:
* landing page view
* table list of commands with links
* quick install (no app launch)
* command line options
* logging in
* video guide
* last 2 release notes (or so)
* affixed/pinned left navigation
* updated layout for navigation/sub navigation
* minimal nav mode after scrolling down (please see issue #16 for details)

**Comment by marians** [comment]
@kordless Can you explain why all reference content should be on one page? With the current content depth, I expect this to be just a bit too much. Imagine docker explaining several of their larger commands on one page (buid, run, ...). We do have some commands which don't need much explanation, but the opposite exists as well.

**Comment by kordless** [comment]
I updated the issue with changes discussed on slack and in @marians comment here. The new layout assumes a multiple page approach for organizing content.

**Comment by marians** [comment]
We'll have to think a bit more about the structure of the Reference section. I'm not happy yet with all that content (e. g. release notes) on the reference landing page, especially since there are more content-rich and important pages which aren't related to commands and don't have a place yet:

http://docs.giantswarm.io/reference/swarm-json/
http://docs.giantswarm.io/reference/registry/

I'll try to shovel cards and provide a draft.

**Comment by marians** [comment]
My current proposal for entire docs structure is here: https://github.com/giantswarm/docs-content/issues/27. With that proposed structure, the reference landing page would have to fulfil a different purpose. Here is a draft for the reference landing page, given the content structure proposed in #27:

![reference](https://cloud.githubusercontent.com/assets/273727/7142310/e7b1124a-e2d7-11e4-971e-6dbe958a08b0.png)

I'm not entirely happy with the "Practical knowledge" sub-header. I'd be happy if we could find a better solution for that.

**Comment by kordless** [comment]
Not happening.
