### ISSUE TITLE
Fix links pointing to /reference/swarm-json/#complete-example

### ISSUE THREAD

**Issue by webwurst** [giantswarm/docs-content#158]
Just noticed that this link to https://docs.giantswarm.io/reference/swarm-json/#complete-example doesn't jumps to the target. Didn't look more into that yet.

**Comment by marians** [comment]
Yes, we renamed the link target according with the headline "Complex example". I'll change the title.

**Comment by marians** [comment]
Can't find any links pointing to `#complete-example`. Closing.
