### ISSUE TITLE
Swarm Update can update whole services

### ISSUE THREAD

**Issue by puja108** [giantswarm/docs-content#160]
Changes based on https://github.com/giantswarm/giantswarm/issues/108#issuecomment-140341215 need to be documented. Blog post can follow later.

**Comment by puja108** [comment]
ping @oponder

**Comment by puja108** [comment]
changes would be mainly to https://github.com/giantswarm/docs-content/blob/master/content/reference/cli/update.md

As this is a bigger change we need to rethink how we restructure that maybe into updateing component images and updating services through swarm.json

**Comment by marians** [comment]
@puja108 Is this issue resolved?

**Comment by puja108** [comment]
I would say yes
