### ISSUE TITLE
Docker Machine replacing Boot2Docker

### ISSUE THREAD

**Issue by grosem** [giantswarm/docs-content#161]
https://docs.giantswarm.io/guides/introduction-to-docker/ recommends installing Boot2Docker. Doing so gets you a "depreciated warning" as Docker Machine as part of the Docker Toolbox is the by Docker recommended tool. (See: https://docs.docker.com/installation/mac/)

I guess you can drop your own detailed guide for Boot2Docker and simply link to the Docker documentation.

**Comment by marians** [comment]
Thanks @grosem for the suggestion. When writing our Docker introduction, we actually saw a benefit in providing a concise guide for our users that focuses on the prerequisites required to work with Giant Swarm. We'll reconsider if this is still the case with Docker machine.
