### ISSUE TITLE
remove CLI OS notice

### ISSUE THREAD

**Issue by puja108** [giantswarm/docs-content#164]
As the open sourcing of the CLI has been a while now, we should remove the note about it. We could maybe leave it in in the main page of the CLI or better integrate it in the introduction text on https://github.com/giantswarm/docs-content/blob/master/content/reference/cli/index.md

**Comment by puja108** [comment]
ping @oponder as we talked about this

**Comment by marians** [comment]
Can we leave it for four weeks? That means we can remove it end of September/beginning of October.

**Comment by puja108** [comment]
ok with that

**Comment by marians** [comment]
I removed the box now.
