### ISSUE TITLE
Component/instance restart logic needs explanation

### ISSUE THREAD

**Issue by marians** [giantswarm/docs-content#168]
IMHO we need a dedicated reference page about the logic behind automated restarts of containers (instances).

Some topics:

- We attempt to restart an instance when the process in it dies, but only when it dies with an exit code unequal to zero.
- What is the maximum number of restarts?
- If this maximum is limited to a specific time frame, how long is this time frame?
- Is the maximum counted by instance or by component?
- Is the max counter resetted by any action like an update or by a manual stop/start?

**Comment by marians** [comment]
Some info from @teemow:

- Restarts are counted on an instance level
- Max 3 restart attempts within 300 seconds
- 1 second delay between attempts

**Comment by marians** [comment]
Question raised by a user: After too many restart attempts, does the instance stay down? Here it could be beneficial to explain the actual status (`DOWN` or `FAILED`).

**Comment by teemow** [comment]
After too many restart attempts the instance stays in failed.
