### ISSUE TITLE
Improve installation instructions for Linux 

### ISSUE THREAD

**Issue by luebken** [giantswarm/docs-content#171]
Feedback via Email from a user:

> the getting started instructions could be improved by highlighting Linux utility program dependencies (curl, git, docker).   curl and git are a bit obvious from reading the getting started script, docker not so much. 
 
https://docs.giantswarm.io/reference/cli/installation/#linux

**Comment by marians** [comment]
Docker isn't a requirement for installing the swarm CLI. Closing this.
