### ISSUE TITLE
Create a documentation video landing page

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#19]
The documentation video page is a loose collection of topics which organize guides containing videos.

![docsvideo](https://cloud.githubusercontent.com/assets/90237/6879360/24071e78-d4b0-11e4-98af-b935254956d7.png)

Creation should include the following, as indicated in the mockup:
* affix/pinned left sub navigation broken down by topic
* featured introductory guide at top (issue #14)
* topic sections with thumbnailed videos in each section
* sections separated by breaks
* some type of reflow layout to make things pretty
* includes new layout for top sub-nav and search
* includes new top-nav minimal view/collapse
* inline video play for each thumbnail
* video title navigates to guide containing indicated video

Guides are implemented via issue #16.

**Comment by marians** [comment]
We have this page (although not exactly in the form as described here). I'll close the issue. The affix menu is a separate issue (https://github.com/giantswarm/docs/issues/132).
