### ISSUE TITLE
Architecture overview is partly wrong or incomplete

### ISSUE THREAD

**Issue by puja108** [giantswarm/docs-content#191]
As for @teemow's feedback there's some issues with the current architecture overview, especially the visuals. The best overview we currently have is in following three images, which would need to be reimplemented to look nicer for docs:
10.000feet: https://docs.google.com/drawings/d/11h1JHJlRVUEZKrMsSx3ZUTcAlZ1ryvF_3IrZFyh5uWs/edit
control plane: https://docs.google.com/drawings/d/109OG4Cm_z7TUTac515_U8Lq6giE3LTdoUPsp4DlRRJo/edit
compute: https://docs.google.com/drawings/d/1_NoQDxID8EnhSqlAospTg5B0faUl9pb1Epy8e7fjdAw/edit

@marians or @oponder should we sit together quickly (this week or early next) to see how we fix the visuals and I write the according new text parts?

**Comment by puja108** [comment]
I'm currently finishing my first draft of the new and revised copy in this PR, @oponder @marians can I get one of you for doing new/updated visuals based on what Timo made in google?

**Comment by puja108** [comment]
RFR @teemow @giantswarm/team-zero the text should be now more in line with the visuals you provided, next step would be new visuals. I changed some of the naming to a bit less confusing.

**Comment by puja108** [comment]
According PR https://github.com/giantswarm/docs-content/pull/193

**Comment by marians** [comment]
Images are updated (part of https://github.com/giantswarm/docs-content/pull/193)

**Comment by marians** [comment]
#193 is merged, so I'm closing this.
