### ISSUE TITLE
Update examples to new Docker base images

### ISSUE THREAD

**Issue by luebken** [giantswarm/docs-content#22]
Docker has updated a couple of base images: http://blog.docker.com/2015/03/updates-available-to-popular-repos-update-your-images/

We need to update our examples and the docs to these new images.

**Comment by puja108** [comment]
didn't we do this already? @marians @luebken

**Comment by luebken** [comment]
yes. we should check if we are done with all repos.

**Comment by puja108** [comment]
I checked all docs Dockerfiles and there's none in there anymore

**Comment by marians** [comment]
Then let's close :)
