### ISSUE TITLE
Provide auto-updates of API reference pages from a rebuild of the API system.

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#24]
It would be great if we could figure out a way to unify reference content for the API, which is currently built from within the API system, with the content we create that exists outside the API system on the documentation pages. 

We may also want to note that using automated content generation could place a single-page requirement on the API reference. Just something to consider moving forward.

**Comment by marians** [comment]
I looked into the state of go-swagger today.

- Swagger has updated their spec (the data model) to version 2, while we are still using 1.2. I highly recommend to not pursue working for the 1.2 spec version.
- Swagger has now their own go tool (http://goswagger.io/, https://github.com/go-swagger/go-swagger) but the documentation is close to non-existent. What we want to do is generate a swagger specification (`swagger generate spec`), but it's unclear where the tool expects the input files. I recommend waiting a few more weeks to let them publish their docs.

So this should be picked up again around beginning of January.
