### ISSUE TITLE
Update reference detail pages

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#26]
Update the reference detail pages currently linked to from http://docs.giantswarm.io/reference/.

![docsreferencedetail](https://cloud.githubusercontent.com/assets/90237/7124161/d8c0244e-e1db-11e4-8d1c-df0db150375d.png)

The changes to these detail pages include the following:

* title includes command being referenced, where applicable (eg. ls: List Applications)
* sample command syntax (swarm <options> <command> format)
* sample output (uses 'bant' user)
* details on lists of items will appear in tables
* additional pages to explore (further reading)
* affixed/pinned left navigation
* updated layout for navigation/sub navigation
* minimal nav mode after scrolling down (please see issue #16 for details)

**Comment by marians** [comment]
Most changes proposed affect the Markdown or frontmatter code. For the rest, I'll create a feature branch with the according CSS, affix menu change and one dummy page to test it.

**Comment by marians** [comment]
I created the new issue in docs for the affix/scrollspy menu part: https://github.com/giantswarm/docs/issues/132

The rest appears as content changes. I'm unassigning myself, since I don't see myself working on the content part for now.

**Comment by kordless** [comment]
Closing. We still need to address the title changes, so another ticket will be opened.
