### ISSUE TITLE
Write a guide explaining best-practices setting up and configuring multi-tenant cluster

### ISSUE THREAD

**Issue by oponder** [giantswarm/docs-content#266]
We should have a "getting access to your rbac enabled cluster" guide.

Which shows just the steps to create a `system:masters` keypair using both happa and gsctl.

The two docs pages that exist currently in relation to this do explain all the things a user would need to know to achieve this, but it requires the user to make the connection. Instead a single page explaining everything step by step would be nice.

**Comment by oponder** [comment]
Would be good as part of this guide, then to also show how to create a user with more limited access. Like once you have the super user, show also how to create a user that only has access to a specific namespace.

**Comment by puja108** [comment]
agree, maybe it could be a best-practice guide to multi-tenancy incl:
1. create (short-lived) cluster-admin credentials to bootstrap roles for your cluster
2. create bindings (and maybe roles) for your users using that cluster-admin
3. create user credentials to send to your users

In 2 we can explain (or link out to other docs page for) namespace isolation and how to map users/teams to their namespaces. We can give examples that look similar to how some of our customers work.

We can mention that 3 is optional if you are using OIDC auth like with Adidas AAD (and link to our AAD docs).

**Comment by marians** [comment]
We just retired this repository. If this issue is still relevant, please create it somewhere else.

**Comment by rossf7** [comment]
@puja108 Do we still want to write this article?
