### ISSUE TITLE
Site and navigation structure

### ISSUE THREAD

**Issue by marians** [giantswarm/docs-content#27]
This is an attempt to come up with a new structure for the docs that can encompass new content (like more guides, API, videos) and can scale in the mid term, integrating some detail proposals by @kordless from various issues.

## Sitemap

When on github.com, click the image for a larger version:

![docs_sitemap_preferred](https://cloud.githubusercontent.com/assets/273727/7140718/28d2d39a-e2cd-11e4-967e-d6c71e4a5f19.png)

Pages with dashed outline are not yet existing.

## Main sections / main navigation items

* Introduction: basic intro, more or less what's currently covered in "What is Giant Swarm", plus video. First page a user should visit when knowing nothing else.
* Guides: Collection of tutorial-style content. Everything that takes users through a process.
* Reference: The place to look up specific information
* Videos: Overview of all videos contained in the docs (mainly in introduction and guides)

## About the reference section

The reference section provides the "single point of truth" for everything a users should want to find out about the CLI, the API but also general concepts behind Giant Swarm.

The content of the reference section will likely grow much larger than currently displayed in the sitemap above. This can be handled by making the reference landing page consist of several link-rich subsections.

## Alternative

In the process I've also explored other options, specifically there is this one version which tried to omit the "reference" section completely. Or, in other words, have a CLI reference and an API reference.

![docs_sitemap_no-reference](https://cloud.githubusercontent.com/assets/273727/7141042/46471f24-e2cf-11e4-8966-5350a2a8c9e7.png)

This led to several problems:

* 6 top menu items instead of 4 (less is easier to integrate)
* Placement of pages like "The Organization Concept", "The Environment Concept" and "Writing Applications for Giant Swarm" was difficult. I attempted it with a section called "Basic Concepts", which isn't really something I can imagine users want to click.
* The important reference pages "Application Configuration" and "Using the Registry" still don't fit well.
* Doesn't scale well. Once we have a new channel besides CLI and API, for example "Web UI", the navigation would have to grow by one item.

**Comment by luebken** [comment]
@kordless wrote:
>Hell, we could leave out the API docs, but I was interested in them for my own videos.

I have to disagree. API docs are overdue and pPrio 1 concerning docs. But I agree there is no need to make it beautiful.

My 2 cents concerning the layout:

I have to second the first layout. At least for the top level / navigation. I am not really sure to put the videos as a top level as it breaks the logic / structure. But I am fine with it if we expect much content there.


@kordless wrote:
> APIs and CLI reference don't go together.

From my point of view the CLI is just a client for the API. Which is the reasoning to put them closely together.

@kordless wrote: 
> Guides are how to do stuff, so you don't go to the CLI Reference to figure out how to install it.

I second that. So we would have a nicely written “Install guide” in the “Guides” and all install options somewhere in “Reference”, right?

@kordless wrote:
> That leaves the main landing page which is what we called 'the wizard'.
> Basically a "i'm in a hurry, let's get going" page.

The landing page should give you a broad overview to easily know where you should keep locking. It’s also a great place for content we like to push.

**Comment by kordless** [comment]
We should close out this ticket if we're satisfied with the current itteration of the docs.

**Comment by marians** [comment]
Thanks!
