### ISSUE TITLE
'Securing your Cluster with RBAC and PSP' page does no render properly some yaml blocks

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/docs-content#288]
I dont know the reason because in the index.md file the blocks look nice but in the website the line breaks are wrong.

https://docs.giantswarm.io/guides/securing-with-rbac-and-psp/#running-applications-that-need-api-access

**Comment by pipo02mix** [comment]
done ^

**Comment by pipo02mix** [comment]
@marians @oponder Although the PR was merged I dont see the changes reflected int he docs website, is there something I need to do?

**Comment by marians** [comment]
Yeah, we need to redeploy manually. I borked the draughtsman configmap and didn't bother to repair it, because we are about to migrate anyway. I'll do it.
