### ISSUE TITLE
Helloworld doesn't handle Sigterm correctly.

### ISSUE THREAD

**Issue by luebken** [giantswarm/docs-content#34]
The current helloworld example https://github.com/giantswarm/helloworld.git goes into failed state when stopping it:
```
swarm stop
Stopping application helloworld...
Application helloworld is failed
```
This is probably due to wrong sigterm handling.

**Comment by kordless** [comment]
This appears to be fixed in bd90eef4d16eb035b9fb06ab784676cccd206fcc.

**Comment by kordless** [comment]
Also, please see: https://github.com/docker/docker/issues/2436.

**Comment by kordless** [comment]
https://github.com/giantswarm/helloworld-formation solves this issue by adding two files: a simplified Dockerfile and a simple server.py file.
