### ISSUE TITLE
'swarmvars' not found using search.

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#58]
Using the search tool on the docs pages, I'm unable to get any results for 'swarmvars' even though that term exists on this page: http://docs.giantswarm.io/reference/cli/create/ in the string 'swarmvars.json'. I think this may be due to elasticsearch not breaking on the '.' inside the filename. Periods at the end of sentences are working for key terms such as 'filename.'

We may want to investigate and provide breaking character information to the search container configuration to alleviate this issue.

**Comment by ZeissS** [comment]
ping @marians

**Comment by marians** [comment]
In case anyone wants to investigate this in my absence, this behaviour is affected by the mapping configured in https://github.com/giantswarm/docs/blob/master/search/config.py#L30-L36.

**Comment by kordless** [comment]
It woudl appear the standard analyzer supports the concept of hostnames (which contain dots). The suggestion is to use the simple analyser instead:

```
"tokenizer": "standard",
```

**Comment by marians** [comment]
Related or near-duplicate: https://github.com/giantswarm/docs/issues/38

**Comment by marians** [comment]
Fix work in progress: https://github.com/giantswarm/docs/pull/136

Asked for help in Google Group/Discourse:
https://groups.google.com/forum/#!topic/elasticsearch/knevi2PyvgM
https://discuss.elastic.co/t/searching-for-foo-should-also-find-occurrence-of-foo-bar/1546
