### ISSUE TITLE
Fix the indentation of the table of contents on the CLI reference overview page.

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#61]
The indentations changes to the CSS made for the API docs has caused some issues for the headers being used on the CLI reference page. Please fix.

**Comment by kordless** [comment]
This issue was related to the use of H3 headers to force the text into the side navigation. As the H3 text was actually intended to link to other content pages, I moved the links into a list and renamed the section to `getting started` with some additional text explaining the steps to 'get started'.

**Comment by marians** [comment]
What's in https://docs.giantswarm.io/reference/cli/ looks good to me, closing.
