### ISSUE TITLE
Update 'swarm' command reference pages

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#62]
From ticket  #26 there were a few items that needed to be completed for the `swarm` CLI command detail pages:

* title should include command being referenced, where applicable (eg. ls: List Applications)
* sample output to follow sample command usage (uses 'bant' user)

The header for the sample output should be `Sample Output`.

**Comment by kordless** [comment]
While I'm at it, I'm doing a general cleanup of the pages for grammar and layout consistency.

**Comment by marians** [comment]
Guess this can be closed as of the latest PR.
