### ISSUE TITLE
Create a public API changelog page

### ISSUE THREAD

**Issue by kordless** [giantswarm/docs-content#63]
This was orginally an bullet item that was part of a lenghty TODO list on a ticket in a private repository for opening up our APIs. Now that work has been completed, and that ticket closed, this ticket serves to save the issue in a location where it will be eventually completed.

The output of this ticket is the following:

* public API changelog page, presumably at `<docs_root>/reference/api/changelog/`
* a defined workflow for updating the changelog during a new API release

**Comment by marians** [comment]
Placeholder is already there in this PR: https://github.com/giantswarm/docs-content/pull/52

**Comment by marians** [comment]
Solved this a while ago. https://docs.giantswarm.io/reference/api/changelog/
