### ISSUE TITLE
doct-content: remove link to ruby guide

### ISSUE THREAD

**Issue by puja108** [giantswarm/docs-content#87]
As we have removed the ruby guide for now, we should also remove the links that are on nearly all firstapp guides until we bring the ruby guide back.

**Comment by marians** [comment]
It appears as if the guide is still there, even linked from the docs start page.
- https://github.com/giantswarm/docs-content/blob/master/content/guides/ruby-on-rails.md
- https://docs.giantswarm.io/guides/ruby-on-rails/

**Comment by puja108** [comment]
ok, I just realized the problem is having underscores instead of dashes, I'll start a PR
